### ISSUE TITLE
can't create bioproject

### ISSUE THREAD

**Issue by elenimijalis** [TAMU-CPT/lims-frontend#22]
{"sample_env":["This field is required."],"sample_phage":["This field is required."]}

**Comment by elenimijalis** [comment]
@erasche I'm assuming sample_phage should be deleted from the bioproject model, but what is sample_env?

**Comment by hexylena** [comment]
I added a sample_env and sample_phage, so that the bioproject could hold both types of things. If it was just env, then the people doing bioinformatics couldn't add phage samples (without their loosely tied env samples), and if it was just phage, we'd have to create those before the wetlab people could add their env samples.
